[
build
]
  command = "npm run build"
  publish = "dist"  # Update this to match your project's build output directory

[
build.environment
]
  NODE_VERSION = "14"  # Adjust this to match your project's Node.js version if needed

[[
redirects
]]
  from = "/*"
  to = "/index.html"
  status = 200